### ISSUE TITLE
Star rating color issue on write review section.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#11]
Bug - Star rating color issue on write review section.
Exp - Star color should be match with store primary color.
Ref Link - https://nimb.ws/yAmqxw

Bug 2 - In mobile UI. Please check image.
Ref lInk - https://nimb.ws/56DPkS

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
@ui-ravishukla 
Bug Not Fixed - Star rating should show in center. Please check link below.
- https://nimb.ws/LtJCcm

**Comment by ankitcedcoss** [comment]
Bug Fixed
