### ISSUE TITLE
Validation spacing issue on contact page.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#14]
Bug - Showing more spacings between field and text.
Exp - https://nimb.ws/XS4pAD
Ref Link - https://nimb.ws/XS4pAD
- https://nimb.ws/sZkC3A

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
@ui-ravishukla 
Bug Not Fixed - please check in video spacing are on decreased.
https://drive.google.com/file/d/1GF1_SBIAqFLF_mH763OVc5hiXZFNtimS/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
