### ISSUE TITLE
Overalapping issue on searchbar and on search page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#16]
Bug - Text overlapping on searchbar dropdown and on search page.
Exp - Text should not get overlap.
Ref Link - https://drive.google.com/file/d/1_mgaALwgeykljZFoLKNJ_L4orSuq5so8/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
Bug Not Fixed - Overlapping issue fixed but product appearing on search is showing in grid view. 
Exp - Search products should appear in list view on search page.
Ref Link - https://drive.google.com/file/d/1Nqvo_gNCg2cYJBrh4AUKf1KeKqvMrXtx/view

**Comment by ui-ravishukla** [comment]
![image](https://user-images.githubusercontent.com/102217972/166655177-52a58d14-2fad-4b9b-8252-9242828b40a4.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
