### ISSUE TITLE
Validation UI issue on Account pages.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#22]
Bug - Validation error showing on place holder section. and text overlapping.
Exp - Validation error must show below text field.
Ref Link - 
- https://drive.google.com/file/d/1icof1aBG1W8IMoT-cZ-q5k8fs30yyD6q/view
- https://nimb.ws/d07uBx
- https://nimb.ws/CEe4tH
- https://nimb.ws/2cEoPu

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Not fixed - 
Exp - Validation error should visible left aligned on fields.
https://drive.google.com/file/d/1_ZEv6f_5S0U1WL1G1iktbBc80aofbJJF/view

**Comment by ui-ravishukla** [comment]
![image](https://user-images.githubusercontent.com/102217972/166665566-2439e598-64ce-4384-ba74-5638a85fa24b.png

**Comment by ankitcedcoss** [comment]
Bug Fixed
