### ISSUE TITLE
Filter UI issue on collection page responsive -  tab

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Encouraging-Truth-Internal-7th-Mar#5]
Bug - Filter text not aligned properly on tab and Not capitalised on page and on filter drawer.
Exp -
- Need to create filter drawer UI on tab.
- Filter and sort text should be capitalised on page and on drawer section.
Ref Link - https://drive.google.com/file/d/1KS1NvbNxpWYb8UaHNVvI5UenbANjkQEX/view

**Comment by ui-chandrashekhar** [comment]
Resolved

**Comment by ankitcedcoss** [comment]
@ui-ravishukla 
Bug Not Fixed - Please check link 
https://nimb.ws/neqKNW

**Comment by ankitcedcoss** [comment]
Bug Fixed
